
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohsin
 */
public final class admin extends javax.swing.JInternalFrame {
     dbclass dbd=new dbclass();
          String url=   dbd.server();
      String id=dbd.serverid();
      String pass=dbd.serverpass();
        public void SetData(Object obj, int row_index, int col_index){
  table.getModel().setValueAt(obj,row_index,col_index);
  }
   public Object GetData(JTable table, int row_index, int col_index){
  return table.getModel().getValueAt(row_index, col_index); }

public void refresh(){
try
        {
         table.getTableHeader().setFont( new Font( "Tahoma" , Font.BOLD, 12 ));
            String query ="SELECT id as 'Username',pass as 'Password',email as 'Email',contact as 'Contact',admin as 'Role'  FROM `login`";       // Create query string to insert name into table
            
            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class
            
            Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials
            
            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
             ResultSet rst1=pst.executeQuery();
            table.setModel (DbUtils.resultSetToTableModel(rst1));
                            int rows= table.getRowCount();
        for(int i=0;i<rows;i++){
            
            int days1 = Integer.parseInt(GetData(table, i, 4).toString());
           String tot7="";
           switch(days1){
               case 0: {tot7="User"; break;} case 1: {tot7="Admin"; break;}  
           
           }
            
            table.setValueAt(tot7, i, 4);
        }

          pst.close();
          rst1.close();
        }
        catch
                (Exception ex)
        {
           JOptionPane.showMessageDialog(null,"Data Error");
        }
}
                                                 // Default Password is empty string

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    
     try
        {
         table.getTableHeader().setFont( new Font( "Tahoma" , Font.BOLD, 12 ));
            String str2=idss.getText();
            String q=passs2.getText();
            String r=emaill.getText();
            String c=cont.getText();
            String query ="SELECT id as 'Username',pass as 'Password',email as 'Email',contact as 'Contact',admin as 'Role' FROM `login`";       // Create query string to insert name into table
            
            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class
            
            Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials
            
            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
             ResultSet rst1=pst.executeQuery();
            table.setModel (DbUtils.resultSetToTableModel(rst1));
                            int rows= table.getRowCount();
        for(int i=0;i<rows;i++){
            
            int days1 = Integer.parseInt(GetData(table, i, 4).toString());
           String tot7="";
           switch(days1){
               case 0: {tot7="User"; break;} case 1: {tot7="Admin"; break;}  }
            table.setValueAt(tot7, i, 4);
        } 
        }
        catch
                (Exception ex)
        {
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        passs2 = new javax.swing.JPasswordField();
        cont = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idss = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emaill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        eror = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pa1 = new javax.swing.JPanel();
        da = new javax.swing.JCheckBox();
        pa = new javax.swing.JCheckBox();
        ma = new javax.swing.JCheckBox();
        ca = new javax.swing.JCheckBox();
        at = new javax.swing.JCheckBox();
        pay = new javax.swing.JCheckBox();
        de = new javax.swing.JCheckBox();
        em = new javax.swing.JCheckBox();
        man = new javax.swing.JCheckBox();
        sh = new javax.swing.JCheckBox();
        le = new javax.swing.JCheckBox();
        im = new javax.swing.JCheckBox();
        ab = new javax.swing.JCheckBox();
        terEmp = new javax.swing.JCheckBox();
        empRep = new javax.swing.JCheckBox();
        holiD = new javax.swing.JCheckBox();
        loan = new javax.swing.JCheckBox();
        advance = new javax.swing.JCheckBox();
        fiYear = new javax.swing.JCheckBox();
        maSystem = new javax.swing.JCheckBox();
        emRep = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        passs = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("User Management");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/mainlogo.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Email", "Contact No.", "User Role"
            }
        ));
        table.setRowHeight(25);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        passs2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passs2.setPreferredSize(new java.awt.Dimension(7, 20));
        passs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passs2ActionPerformed(evt);
            }
        });

        cont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cont.setPreferredSize(new java.awt.Dimension(7, 20));
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contact No.:");

        idss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idss.setMinimumSize(new java.awt.Dimension(7, 20));
        idss.setPreferredSize(new java.awt.Dimension(7, 150));
        idss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idssActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        emaill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emaill.setPreferredSize(new java.awt.Dimension(7, 20));
        emaill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emaillActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Repeat Password:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-ic.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.setPreferredSize(new java.awt.Dimension(95, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        eror.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eror.setForeground(new java.awt.Color(255, 0, 51));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-ic.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setPreferredSize(new java.awt.Dimension(95, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pa1.setBackground(new java.awt.Color(255, 255, 255));
        pa1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select User Options"));

        da.setBackground(new java.awt.Color(255, 255, 255));
        da.setSelected(true);
        da.setText("Database Setting");

        pa.setBackground(new java.awt.Color(255, 255, 255));
        pa.setSelected(true);
        pa.setText("Path Setting");

        ma.setBackground(new java.awt.Color(255, 255, 255));
        ma.setSelected(true);
        ma.setText("Machine Setting");
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });

        ca.setBackground(new java.awt.Color(255, 255, 255));
        ca.setSelected(true);
        ca.setText("Calculate Report");
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        at.setBackground(new java.awt.Color(255, 255, 255));
        at.setSelected(true);
        at.setText("Attendance report");
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setSelected(true);
        pay.setText("Payroll Report");

        de.setBackground(new java.awt.Color(255, 255, 255));
        de.setSelected(true);
        de.setText("Department ");

        em.setBackground(new java.awt.Color(255, 255, 255));
        em.setSelected(true);
        em.setText("Employee ");

        man.setBackground(new java.awt.Color(255, 255, 255));
        man.setSelected(true);
        man.setText("Manual Attendance");

        sh.setBackground(new java.awt.Color(255, 255, 255));
        sh.setSelected(true);
        sh.setText("Shift");

        le.setBackground(new java.awt.Color(255, 255, 255));
        le.setSelected(true);
        le.setText("Leave");

        im.setBackground(new java.awt.Color(255, 255, 255));
        im.setSelected(true);
        im.setText("Import Data");

        ab.setBackground(new java.awt.Color(255, 255, 255));
        ab.setSelected(true);
        ab.setText("About");

        terEmp.setBackground(new java.awt.Color(255, 255, 255));
        terEmp.setSelected(true);
        terEmp.setText("Terminated Employee");
        terEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terEmpActionPerformed(evt);
            }
        });

        empRep.setBackground(new java.awt.Color(255, 255, 255));
        empRep.setSelected(true);
        empRep.setText("Employee Report");
        empRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRepActionPerformed(evt);
            }
        });

        holiD.setBackground(new java.awt.Color(255, 255, 255));
        holiD.setSelected(true);
        holiD.setText("Holiday");
        holiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holiDActionPerformed(evt);
            }
        });

        loan.setBackground(new java.awt.Color(255, 255, 255));
        loan.setSelected(true);
        loan.setText("Loan");
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });

        advance.setBackground(new java.awt.Color(255, 255, 255));
        advance.setSelected(true);
        advance.setText("Advance");
        advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceActionPerformed(evt);
            }
        });

        fiYear.setBackground(new java.awt.Color(255, 255, 255));
        fiYear.setSelected(true);
        fiYear.setText("Financial year");
        fiYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiYearActionPerformed(evt);
            }
        });

        maSystem.setBackground(new java.awt.Color(255, 255, 255));
        maSystem.setSelected(true);
        maSystem.setText("Mailing System");
        maSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSystemActionPerformed(evt);
            }
        });

        emRep.setBackground(new java.awt.Color(255, 255, 255));
        emRep.setSelected(true);
        emRep.setText("Terminated Employee Report");
        emRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pa1Layout = new javax.swing.GroupLayout(pa1);
        pa1.setLayout(pa1Layout);
        pa1Layout.setHorizontalGroup(
            pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa1Layout.createSequentialGroup()
                        .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(im)
                            .addComponent(sh)
                            .addComponent(ca)
                            .addComponent(pay)
                            .addComponent(ma)
                            .addComponent(em)
                            .addComponent(da)
                            .addComponent(empRep)
                            .addComponent(loan)
                            .addComponent(fiYear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(le)
                                .addComponent(ab)
                                .addComponent(de)
                                .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(at, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(man)
                                .addComponent(holiD)
                                .addComponent(advance)
                                .addComponent(terEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addComponent(maSystem))
                        .addGap(45, 45, 45))
                    .addGroup(pa1Layout.createSequentialGroup()
                        .addComponent(emRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pa1Layout.setVerticalGroup(
            pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(da)
                    .addComponent(pa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ma)
                    .addComponent(at))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca)
                    .addComponent(de))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay)
                    .addComponent(man))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(em)
                    .addComponent(le))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sh)
                    .addComponent(ab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(im)
                    .addComponent(terEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empRep)
                    .addComponent(holiD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loan)
                    .addComponent(advance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiYear)
                    .addComponent(maSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emRep)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Role"));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("User");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Admin");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Create Password:");

        passs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passs.setPreferredSize(new java.awt.Dimension(7, 20));
        passs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel-btn-icon-20.png"))); // NOI18N
        jButton4.setText("Close");
        jButton4.setPreferredSize(new java.awt.Dimension(95, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mohsin\\Documents\\NetBeansProjects\\HumanResources_7jan\\src\\update-ic.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(95, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passs2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84)
                                .addComponent(emaill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eror, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)
                        .addComponent(pa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idss, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(passs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(eror, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        idss.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel)table.getModel();

        // get the selected row index
        int selectedRowIndex = table.getSelectedRow();

        // set the selected row data into jtextfields
        idss.setText(model.getValueAt(selectedRowIndex, 0).toString());
        emaill.setText(model.getValueAt(selectedRowIndex, 2).toString());
        passs2.setText(model.getValueAt(selectedRowIndex, 1).toString());
        cont.setText(model.getValueAt(selectedRowIndex, 3).toString());
                try
        {

            String query = "SELECT `id`, `pass`, `email`, `contact`, `admin`, `data`, `path`, `machine`, `calculate`, `attendance`, `payroll`, `depart`, `employee`, `manual`, `shift`, `leavemanage`, `import`, `help`, `termin_emp`, `empRpt`, `holi`, `loan`, `adva`, `finan`, `mail`, `termemprpt`  FROM login WHERE id='"+idss.getText()+"' ";             // Create query string to insert name into table

            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

            Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
            ResultSet result = pst.executeQuery();
            //                                    Execute Query
            //pst.setString(1,str1);
            //          pst.setString(2,p);
            // Close the open connection
            if(result.next()){
            int a1=result.getInt("admin");
                if(a1 == 1){jRadioButton1.setSelected(true);
                       pa1.setEnabled(false);
       //ad.setEnabled(false);
       da.setEnabled(false);pa.setEnabled(false);ma.setEnabled(false);
                ca.setEnabled(false);at.setEnabled(false);pay.setEnabled(false);de.setEnabled(false);em.setEnabled(false);man.setEnabled(false);
                sh.setEnabled(false);le.setEnabled(false);im.setEnabled(false);ab.setEnabled(false);
                terEmp.setEnabled(false);empRep.setEnabled(false);
                holiD.setEnabled(false);loan.setEnabled(false);advance.setEnabled(false);fiYear.setEnabled(false);maSystem.setEnabled(false);emRep.setEnabled(false);

                
                
                }else{jRadioButton2.setSelected(true);
                pa1.setEnabled(true);
                        //ad.setEnabled(true);
                        da.setEnabled(true);pa.setEnabled(true);ma.setEnabled(true);
                ca.setEnabled(true);at.setEnabled(true);pay.setEnabled(true);de.setEnabled(true);em.setEnabled(true);man.setEnabled(true);
                sh.setEnabled(true);le.setEnabled(true);im.setEnabled(true);ab.setEnabled(true);
   terEmp.setEnabled(true);empRep.setEnabled(true);
 holiD.setEnabled(true);loan.setEnabled(true);advance.setEnabled(true);fiYear.setEnabled(true);maSystem.setEnabled(true);emRep.setEnabled(true);
                }
                int a2=result.getInt("data");
                if(a2 == 0){da.setSelected(false);}else{da.setSelected(true);}
                int a3=result.getInt("path");
                if(a3 == 0){pa.setSelected(false);}else{pa.setSelected(true);}
                int a4=result.getInt("machine");
                if(a4 == 0){ma.setSelected(false);}else{ma.setSelected(true);}
                int a5=result.getInt("calculate");
                if(a5 == 0){ca.setSelected(false);}else{ca.setSelected(true);}
                int a6=result.getInt("attendance");
                if(a6 == 0){at.setSelected(false);} else{at.setSelected(true);}
                int a7=result.getInt("payroll");
                if(a7 == 0){pay.setSelected(false);}else{pay.setSelected(true);}
                int a8=result.getInt("depart");
                if(a8 == 0){de.setSelected(false);}else{de.setSelected(true);}
                int a9=result.getInt("employee");
                if(a9 == 0){em.setSelected(false);}else{em.setSelected(true);}
                int a10=result.getInt("shift");
                if(a10 == 0){sh.setSelected(false);}else{sh.setSelected(true);}
                int a11=result.getInt("manual");
                if(a11 == 0){man.setSelected(false);}else{man.setSelected(true);}
                int a12=result.getInt("leavemanage");
                if(a12 == 0){le.setSelected(false);}else{le.setSelected(true);}
                int a13=result.getInt("import");
                if(a13 == 0){im.setSelected(false);}else{im.setSelected(true);}
                int a14=result.getInt("help");
                if(a14 == 0){ab.setSelected(false);}else{ab.setSelected(true);}
                  
                int a15=result.getInt("termin_emp");
                if(a15 == 0){terEmp.setSelected(false);}else{terEmp.setSelected(true);}
                int a16=result.getInt("empRpt");
                if(a16 == 0){empRep.setSelected(false);}else{empRep.setSelected(true);}
                int a17=result.getInt("holi");
                if(a17 == 0){holiD.setSelected(false);}else{holiD.setSelected(true);}
                int a18=result.getInt("loan");
                if(a18 == 0){loan.setSelected(false);}else{loan.setSelected(true);}
                int a19=result.getInt("adva");
                if(a19 == 0){advance.setSelected(false);}else{advance.setSelected(true);}
                int a20=result.getInt("finan");
                if(a20 == 0){fiYear.setSelected(false);}else{fiYear.setSelected(true);}
                int a21=result.getInt("mail");
                if(a21 == 0){maSystem.setSelected(false);}else{maSystem.setSelected(true);}
                int a22=result.getInt("termemprpt");
                if(a22 == 0){emRep.setSelected(false);}else{emRep.setSelected(true);}
                // `termin_emp`, `empRpt`, `holi`, `loan`, `adva`, `finan`, `mail`, `termemprpt`
            }}catch(Exception e){}

        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void passs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passs2ActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contActionPerformed

    private void idssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idssActionPerformed

    private void emaillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emaillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emaillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                        // Default Password is empty string
String str2=idss.getText();
            String q=passs2.getText();
            String r=emaill.getText();
            String c=cont.getText();int a1=0,a2=0,a3=0,a4=0,a5=0,a6=0,a7=0,a8=0,a9=0,a10=0,a11=0,a12=0,a13=0,a14=0,a15=0,a16=0,a17=0,a18=0,a19=0,a20=0,a21=0,a22=0;
            String u=passs.getText();
            if( q.matches(u) ){
            if(str2.isEmpty() || q.isEmpty() || r.isEmpty() || c.isEmpty() )
            {JOptionPane.showMessageDialog(null,"Missing information","Error",JOptionPane.ERROR_MESSAGE);}
            else{   
                //if(ad.isSelected()){a1=1;}
                if(da.isSelected()){a2=1;}if(pa.isSelected()){a3=1;}if(ma.isSelected()){a4=1;}
                if(ca.isSelected()){a5=1;}if(at.isSelected()){a6=1;}if(pay.isSelected()){a7=1;}if(de.isSelected()){a8=1;}
                if(em.isSelected()){a9=1;}if(man.isSelected()){a10=1;}if(sh.isSelected()){a11=1;}if(le.isSelected()){a12=1;}
                if(im.isSelected()){a13=1;}if(ab.isSelected()){a14=1;}
                if(terEmp.isSelected()){a15=1;}if(empRep.isSelected()){a16=1;}
                if(holiD.isSelected()){a17=1;}if(loan.isSelected()){a18=1;}if(advance.isSelected()){a19=1;}if(fiYear.isSelected()){a20=1;}
                if(maSystem.isSelected()){a21=1;}if(emRep.isSelected()){a22=1;}
                
                
if (jRadioButton1.isSelected()){a1=1;a2=1;a3=1;a4=4;a5=1;a6=1;a7=1;a8=1;a9=1;a10=1;a11=1;a12=1;a13=1;a14=1;
                                a15=1;a16=1;a17=1;a18=1;a19=1;a20=1;a21=1;a22=1;
}
if (jRadioButton2.isSelected()){a1=0; }            
try
        {
         table.getTableHeader().setFont( new Font( "Tahoma" , Font.BOLD, 12 ));
            
            String query ="INSERT INTO `login` VALUES ('"+str2+"','"+q+"','"+r+"','"+c+"','"+a1+"','"+a2+"','"+a3+"','"+a4+"','"+a5+"','"+a6+"','"+a7+"','"+a8+"','"+a9+"','"+a10+"','"+a11+"','"+a12+"','"+a13+"','"+a14+"','"+a15+"','"+a16+"','"+a17+"','"+a18+"','"+a19+"','"+a20+"','"+a21+"','"+a22+"')";       // Create query string to insert name into table

            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

            Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
            pst.executeUpdate(query);

            // Close the open connectio
            JOptionPane.showMessageDialog(null,"Data insert successfully ");
            admin abcdef=new admin();
            abcdef.validate();
        }
        catch
        (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Data Invalid","Error",JOptionPane.ERROR_MESSAGE);
        }
        refresh();}}
            else{JOptionPane.showMessageDialog(null,"Password does not match","Error",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
         table.getTableHeader().setFont( new Font( "Tahoma" , Font.BOLD, 12 ));
            String str2=idss.getText();
            
            String query ="delete from `login` where id='"+str2+"'";       // Create query string to insert name into table

            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

            Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
            pst.executeUpdate(query);

            // Close the open connectio
            JOptionPane.showMessageDialog(null,"Admin Removed");
            admin abcdef=new admin();
            abcdef.validate();
        }
        catch
        (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Data invalid","Error",JOptionPane.ERROR_MESSAGE);
        }
        refresh();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        pa1.setEnabled(true);
                        //ad.setEnabled(true);
                        da.setEnabled(true);pa.setEnabled(true);ma.setEnabled(true);
                ca.setEnabled(true);at.setEnabled(true);pay.setEnabled(true);de.setEnabled(true);em.setEnabled(true);man.setEnabled(true);
                sh.setEnabled(true);le.setEnabled(true);im.setEnabled(true);ab.setEnabled(true);                terEmp.setEnabled(true);empRep.setEnabled(true);
                holiD.setEnabled(true);loan.setEnabled(true);advance.setEnabled(true);fiYear.setEnabled(true);maSystem.setEnabled(true);emRep.setEnabled(true);

    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
       pa1.setEnabled(false);
       //ad.setEnabled(false);
       da.setEnabled(false);pa.setEnabled(false);ma.setEnabled(false);
                ca.setEnabled(false);at.setEnabled(false);pay.setEnabled(false);de.setEnabled(false);em.setEnabled(false);man.setEnabled(false);
                sh.setEnabled(false);le.setEnabled(false);im.setEnabled(false);ab.setEnabled(false);                terEmp.setEnabled(false);empRep.setEnabled(false);
                holiD.setEnabled(false);loan.setEnabled(false);advance.setEnabled(false);fiYear.setEnabled(false);maSystem.setEnabled(false);emRep.setEnabled(false);

    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        pa1.setEnabled(false);
        
       //ad.setEnabled(false);
       da.setEnabled(false);pa.setEnabled(false);ma.setEnabled(false);
                ca.setEnabled(false);at.setEnabled(false);pay.setEnabled(false);de.setEnabled(false);em.setEnabled(false);man.setEnabled(false);
                sh.setEnabled(false);le.setEnabled(false);im.setEnabled(false);ab.setEnabled(false);                terEmp.setEnabled(false);empRep.setEnabled(false);
                holiD.setEnabled(false);loan.setEnabled(false);advance.setEnabled(false);fiYear.setEnabled(false);maSystem.setEnabled(false);emRep.setEnabled(false);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       pa1.setEnabled(true);
       //ad.setEnabled(true);
       da.setEnabled(true);pa.setEnabled(true);ma.setEnabled(true);
                ca.setEnabled(true);at.setEnabled(true);pay.setEnabled(true);de.setEnabled(true);em.setEnabled(true);man.setEnabled(true);
                sh.setEnabled(true);le.setEnabled(true);im.setEnabled(true);ab.setEnabled(true);
                                terEmp.setEnabled(true);empRep.setEnabled(true);
                holiD.setEnabled(true);loan.setEnabled(true);advance.setEnabled(true);fiYear.setEnabled(true);maSystem.setEnabled(true);emRep.setEnabled(true);

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void passsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str2=idss.getText();
            String q=passs2.getText();
            String r=emaill.getText();
            String c=cont.getText();int a1=0,a2=0,a3=0,a4=0,a5=0,a6=0,a7=0,a8=0,a9=0,a10=0,a11=0,a12=0,a13=0,a14=0,a15=0,a16=0,a17=0,a18=0,a19=0,a20=0,a21=0,a22=0;
            String u=passs.getText();
            if( q.matches(u) ){
            if(str2.isEmpty() || q.isEmpty() || r.isEmpty() || c.isEmpty() )
            {JOptionPane.showMessageDialog(null,"Please Fill Complete Details","Error",JOptionPane.ERROR_MESSAGE);}
            else{   
                //if(ad.isSelected()){a1=1;}
                if(da.isSelected()){a2=1;}if(pa.isSelected()){a3=1;}if(ma.isSelected()){a4=1;}
                if(ca.isSelected()){a5=1;}if(at.isSelected()){a6=1;}if(pay.isSelected()){a7=1;}if(de.isSelected()){a8=1;}
                if(em.isSelected()){a9=1;}if(man.isSelected()){a10=1;}if(sh.isSelected()){a11=1;}if(le.isSelected()){a12=1;}
                if(im.isSelected()){a13=1;}
                if(ab.isSelected()){a14=1;}
                if(terEmp.isSelected()){a15=1;}if(empRep.isSelected()){a16=1;}
                if(holiD.isSelected()){a17=1;}if(loan.isSelected()){a18=1;}if(advance.isSelected()){a19=1;}if(fiYear.isSelected()){a20=1;}
                if(maSystem.isSelected()){a21=1;}if(emRep.isSelected()){a22=1;}
            }
if (jRadioButton1.isSelected()){a1=1;a2=1;a3=1;a4=4;a5=1;a6=1;a7=1;a8=1;a9=1;a10=1;a11=1;a12=1;a13=1;a14=1;a15=1;a16=1;a17=1;a18=1;a19=1;a20=1;a21=1;a22=1;}
if (jRadioButton2.isSelected()){a1=0; }            
            
        try
        {   String query ="UPDATE `login` SET `pass`='"+q+"',`email`='"+r+"',`contact`='"+c+"',`admin`='"+a1+"',`data`='"+a2+"',`path`='"+a3+"',`machine`='"+a4+"',`calculate`='"+a5+"',`attendance`='"+a6+"',`payroll`='"+a7+"',`depart`='"+a8+"',`employee`='"+a9+"',`manual`='"+a10+"',`shift`='"+a11+"',`leavemanage`='"+a12+"',`import`='"+a13+"',`help`='"+a14+"',`termin_emp`='"+a15+"',`empRpt`='"+a16+"',`holi`='"+a17+"',`loan`='"+a18+"',`adva`='"+a19+"',`finan`='"+a20+"',`mail`='"+a21+"',`termemprpt`='"+a22+"' where id='"+str2+"'";       // Create query string to insert name into table

            Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

            Connection con = DriverManager.getConnection(url,id,pass);
            PreparedStatement pst= con.prepareStatement(query);                             // Create statement
            pst.executeUpdate(query);

            // Close the open connectio
            JOptionPane.showMessageDialog(null,"Update Successfully");
            refresh();

        }
        catch
        (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Update not successful","Error",JOptionPane.ERROR_MESSAGE);
        }
            }else{JOptionPane.showMessageDialog(null,"Password does not match","Error",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void terEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terEmpActionPerformed

    private void empRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empRepActionPerformed

    private void holiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holiDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holiDActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanActionPerformed

    private void advanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceActionPerformed

    private void fiYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiYearActionPerformed

    private void maSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSystemActionPerformed

    private void emRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emRepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ab;
    private javax.swing.JCheckBox advance;
    private javax.swing.JCheckBox at;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox ca;
    private javax.swing.JTextField cont;
    private javax.swing.JCheckBox da;
    private javax.swing.JCheckBox de;
    private javax.swing.JCheckBox em;
    private javax.swing.JCheckBox emRep;
    private javax.swing.JTextField emaill;
    private javax.swing.JCheckBox empRep;
    private javax.swing.JLabel eror;
    private javax.swing.JCheckBox fiYear;
    private javax.swing.JCheckBox holiD;
    private javax.swing.JTextField idss;
    private javax.swing.JCheckBox im;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox le;
    private javax.swing.JCheckBox loan;
    private javax.swing.JCheckBox ma;
    private javax.swing.JCheckBox maSystem;
    private javax.swing.JCheckBox man;
    private javax.swing.JCheckBox pa;
    private javax.swing.JPanel pa1;
    private javax.swing.JPasswordField passs;
    private javax.swing.JPasswordField passs2;
    private javax.swing.JCheckBox pay;
    private javax.swing.JCheckBox sh;
    private javax.swing.JTable table;
    private javax.swing.JCheckBox terEmp;
    // End of variables declaration//GEN-END:variables
}
