
import java.awt.Toolkit;
import java.text.DateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohsin
 */
public class mainMenu extends javax.swing.JInternalFrame {
  Date now = new Date();int i=0;
          
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        systemTime.setText("Today is "+DateFormat.getDateTimeInstance(
            DateFormat.MEDIUM, DateFormat.SHORT).format(now) ) ;
    Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setResizable(false);
        
        this.setSize(xsize,680);
        
        //loginform form=new loginform(); form.setVisible(false);
        //if(form.atti() == 0 ){attendance.setEnabled(false);}
       // if(form.manuali() == 0 ){manual.setEnabled(false);}
       //if(form.shifti() == 0 ){shift.setEnabled(false);}
        //if(form.payroli() == 0 ){payroll.setEnabled(false);}
        //if(form.loani() == 0 ){payroll1.setEnabled(false);}
        //if(form.depi() == 0 ){department.setEnabled(false);}
        //if(form.leavei() == 0 ){manual1.setEnabled(false);}
        //if(form.empi() == 0 ){employees.setEnabled(false);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        a12 = new javax.swing.JLabel();
        employees = new javax.swing.JButton();
        shift = new javax.swing.JButton();
        manual = new javax.swing.JButton();
        attendance = new javax.swing.JButton();
        payroll = new javax.swing.JButton();
        department = new javax.swing.JButton();
        manual1 = new javax.swing.JButton();
        payroll1 = new javax.swing.JButton();
        a13 = new javax.swing.JLabel();
        systemTime = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setTitle("Quick Menu");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/mainlogo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1300, 900));
        setPreferredSize(new java.awt.Dimension(900, 680));

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane3.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane3.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane3.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main-image7.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 480, 490));

        a12.setBackground(new java.awt.Color(255, 149, 65));
        a12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        a12.setForeground(new java.awt.Color(255, 255, 255));
        a12.setText("Quick Menu");
        a12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        a12.setDoubleBuffered(true);
        a12.setFocusTraversalPolicyProvider(true);
        a12.setOpaque(true);

        employees.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employees.png"))); // NOI18N
        employees.setText("Employees");
        employees.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        employees.setContentAreaFilled(false);
        employees.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employees.setMaximumSize(new java.awt.Dimension(149, 41));
        employees.setMinimumSize(new java.awt.Dimension(149, 41));
        employees.setPreferredSize(new java.awt.Dimension(149, 41));
        employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesActionPerformed(evt);
            }
        });

        shift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shifts.png"))); // NOI18N
        shift.setText("Shifts Management");
        shift.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        shift.setContentAreaFilled(false);
        shift.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shift.setMaximumSize(new java.awt.Dimension(149, 41));
        shift.setMinimumSize(new java.awt.Dimension(149, 41));
        shift.setPreferredSize(new java.awt.Dimension(149, 41));
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });

        manual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manual-attnd.png"))); // NOI18N
        manual.setText("Manual Attendance");
        manual.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        manual.setContentAreaFilled(false);
        manual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manual.setMaximumSize(new java.awt.Dimension(149, 41));
        manual.setMinimumSize(new java.awt.Dimension(149, 41));
        manual.setPreferredSize(new java.awt.Dimension(149, 41));
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        attendance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attnd-report.png"))); // NOI18N
        attendance.setText("Attendance Report");
        attendance.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        attendance.setContentAreaFilled(false);
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        attendance.setMaximumSize(new java.awt.Dimension(149, 41));
        attendance.setMinimumSize(new java.awt.Dimension(149, 41));
        attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceActionPerformed(evt);
            }
        });

        payroll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrol-report.png"))); // NOI18N
        payroll.setText("Payroll Report");
        payroll.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        payroll.setContentAreaFilled(false);
        payroll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payroll.setMaximumSize(new java.awt.Dimension(149, 41));
        payroll.setMinimumSize(new java.awt.Dimension(149, 41));
        payroll.setPreferredSize(new java.awt.Dimension(149, 41));
        payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollActionPerformed(evt);
            }
        });

        department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/departments.png"))); // NOI18N
        department.setText("Departments");
        department.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        department.setContentAreaFilled(false);
        department.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        manual1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manual1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leave-mgm.png"))); // NOI18N
        manual1.setText("Leave Management");
        manual1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        manual1.setContentAreaFilled(false);
        manual1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manual1.setMaximumSize(new java.awt.Dimension(149, 41));
        manual1.setMinimumSize(new java.awt.Dimension(149, 41));
        manual1.setPreferredSize(new java.awt.Dimension(149, 41));
        manual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manual1ActionPerformed(evt);
            }
        });

        payroll1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payroll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loan-icon.png"))); // NOI18N
        payroll1.setText("Loan Management");
        payroll1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)), null));
        payroll1.setContentAreaFilled(false);
        payroll1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payroll1.setMaximumSize(new java.awt.Dimension(149, 41));
        payroll1.setMinimumSize(new java.awt.Dimension(149, 41));
        payroll1.setPreferredSize(new java.awt.Dimension(149, 41));
        payroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payroll1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(a12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(employees, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(shift, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(manual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(attendance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(payroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(department, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(manual1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(payroll1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manual1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payroll, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manual, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(employees, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {attendance, department, employees, manual, manual1, payroll, payroll1, shift});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {attendance, department, employees, manual, manual1, payroll, payroll1, shift});

        jPanel2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 270, 620));

        a13.setBackground(new java.awt.Color(0, 0, 0));
        a13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        a13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quick-menu.png"))); // NOI18N
        a13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        a13.setFocusable(false);
        jPanel2.add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, -1));

        systemTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        systemTime.setForeground(new java.awt.Color(252, 126, 1));
        systemTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(systemTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesActionPerformed
        //jDesktopPane3.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        employ a=new employ();
       a.setVisible(true);
       this.getDesktopPane().add(a);
      //     a.show();  
      try{
a.setSelected(true);}catch(Exception e){}
    }//GEN-LAST:event_employeesActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
        shift a=new shift();
  a.setVisible(true);
       this.getDesktopPane().add(a);
      try{
a.setSelected(true);}catch(Exception e){}       //this.dispose();  //   setContentPane(form);
    }//GEN-LAST:event_shiftActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        //jDesktopPane3.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        manualatt a=new manualatt();
  a.setVisible(true);
       this.getDesktopPane().add(a);
       try{
a.setSelected(true);}catch(Exception e){} 
    }//GEN-LAST:event_manualActionPerformed

    private void attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceActionPerformed
        //         jDesktopPane3.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
       payroll a=new payroll();
  a.setVisible(true);
       this.getDesktopPane().add(a);  try{
a.setSelected(true);}catch(Exception e){}
       
    
    }//GEN-LAST:event_attendanceActionPerformed

    private void payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollActionPerformed
        //  jDesktopPane3.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        payrollsheet2 a=new payrollsheet2();
 a.setVisible(true);
       this.getDesktopPane().add(a);  try{
a.setSelected(true);}catch(Exception e){}
    }//GEN-LAST:event_payrollActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed

        depart a=new depart();
        a.setVisible(true);
       this.getDesktopPane().add(a);  try{
a.setSelected(true);}catch(Exception e){}
    }//GEN-LAST:event_departmentActionPerformed

    private void manual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manual1ActionPerformed
        leavemanage a=new leavemanage();
        //jDesktopPane3.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
  a.setVisible(true);
       this.getDesktopPane().add(a);  try{
a.setSelected(true);}catch(Exception e){}
       //this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_manual1ActionPerformed

    private void payroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payroll1ActionPerformed
        Loan_manage a=new Loan_manage();
  a.setVisible(true);
       this.getDesktopPane().add(a);  try{
a.setSelected(true);}catch(Exception e){}
               //this.dispose();
    }//GEN-LAST:event_payroll1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    public javax.swing.JButton attendance;
    public javax.swing.JButton department;
    public javax.swing.JButton employees;
    protected javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    protected javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JPanel jPanel2;
    public javax.swing.JButton manual;
    public javax.swing.JButton manual1;
    public javax.swing.JButton payroll;
    public javax.swing.JButton payroll1;
    public javax.swing.JButton shift;
    private javax.swing.JLabel systemTime;
    // End of variables declaration//GEN-END:variables
}
