
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohsin
 */

public class shiftdaystable extends javax.swing.JFrame {
     dbclass dbd=new dbclass();
          String url=   dbd.server();
      String id=dbd.serverid();
      String pass=dbd.serverpass();
    String d1=""; String d2="";
shift art=new shift();
    public void reset(){
       String url="jdbc:mysql://localhost:3306/hrm";
        String id="root";
        String pass="1234"; 
    try{
         shift abd=new shift();
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,id,pass);
        String query="select Sch_ID as 'Shift ID',Name as 'Shift Name',timein as 'Start Time',timeout 'End Time' from shift";
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rst1=pst.executeQuery();
        shift.table.setModel (DbUtils.resultSetToTableModel(rst1));
           
         art.reset();
        
    }
     catch(Exception ex)
     {}
}
        
    /**
     * Creates new form shiftdaystable
     */
    public shiftdaystable() {
        initComponents();
         this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Mohsin\\Documents\\NetBeansProjects\\HumanResources_7jan\\src\\mainlogo.png"));
        this.setAlwaysOnTop(true);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,id,pass);
            PreparedStatement pst=conn.prepareStatement("SELECT name FROM `shift`");
           
            ResultSet rst1=pst.executeQuery();
            
           while(rst1.next()){
               shift1.addItem(rst1.getString("name"));
               reset();
               
           }
            
                    }
        catch(Exception ex){
        
        }
try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,id,pass);
            PreparedStatement pst=conn.prepareStatement("SELECT name FROM `num_run`");
           
            ResultSet rst1=pst.executeQuery();
            
           while(rst1.next()){
               schedule1.addItem(rst1.getString("name"));
               
           }
            
                    }
        catch(Exception ex){
        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        scheduleid = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        shift1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        mon = new javax.swing.JCheckBox();
        tues = new javax.swing.JCheckBox();
        wed = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        thurs = new javax.swing.JCheckBox();
        schedule1 = new javax.swing.JComboBox<>();
        fri = new javax.swing.JCheckBox();
        sat = new javax.swing.JCheckBox();
        sun = new javax.swing.JCheckBox();
        shiftid = new javax.swing.JComboBox<>();
        sstarttime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        sendtime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        eror = new javax.swing.JLabel();
        overtime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel19 = new javax.swing.JLabel();
        IOT = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        LE = new lu.tudor.santec.jtimechooser.JTimeChooser();
        EE = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        EA = new lu.tudor.santec.jtimechooser.JTimeChooser();
        EB = new lu.tudor.santec.jtimechooser.JTimeChooser();
        nights = new javax.swing.JCheckBox();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lunchin = new lu.tudor.santec.jtimechooser.JTimeChooser();
        lunchout = new lu.tudor.santec.jtimechooser.JTimeChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Arrange Shifts");
        setAlwaysOnTop(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scheduleid.setEditable(true);
        scheduleid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scheduleid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Shift Id" }));
        jPanel5.add(scheduleid, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 112, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Select Shift Segment:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 82, -1, 20));

        shift1.setEditable(true);
        shift1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        shift1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Shift Selected" }));
        shift1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shift1ActionPerformed(evt);
            }
        });
        jPanel5.add(shift1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 85, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Select Days");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 182, 90, -1));

        mon.setBackground(new java.awt.Color(255, 255, 255));
        mon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mon.setSelected(true);
        mon.setText("Monday");
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        jPanel5.add(mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 182, -1, -1));

        tues.setBackground(new java.awt.Color(255, 255, 255));
        tues.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tues.setSelected(true);
        tues.setText("Tuesday");
        tues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesActionPerformed(evt);
            }
        });
        jPanel5.add(tues, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 181, -1, -1));

        wed.setBackground(new java.awt.Color(255, 255, 255));
        wed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wed.setSelected(true);
        wed.setText("Wednesday");
        jPanel5.add(wed, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 182, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Select Shift:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 112, 120, 20));

        thurs.setBackground(new java.awt.Color(255, 255, 255));
        thurs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        thurs.setSelected(true);
        thurs.setText("Thursday");
        jPanel5.add(thurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 182, -1, -1));

        schedule1.setEditable(true);
        schedule1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        schedule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Shift Selected" }));
        schedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule1ActionPerformed(evt);
            }
        });
        jPanel5.add(schedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 112, 150, -1));

        fri.setBackground(new java.awt.Color(255, 255, 255));
        fri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fri.setSelected(true);
        fri.setText("Friday");
        jPanel5.add(fri, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 182, -1, -1));

        sat.setBackground(new java.awt.Color(255, 255, 255));
        sat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sat.setSelected(true);
        sat.setText("Saturday");
        jPanel5.add(sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 182, -1, -1));

        sun.setBackground(new java.awt.Color(255, 255, 255));
        sun.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sun.setSelected(true);
        sun.setText("Sunday");
        jPanel5.add(sun, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 182, -1, -1));

        shiftid.setEditable(true);
        shiftid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        shiftid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Shift Id " }));
        jPanel5.add(shiftid, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 85, -1, -1));
        jPanel5.add(sstarttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));
        jPanel5.add(sendtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Over Time");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Start Time");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 232, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("End Time");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 262, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-ic.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 423, 80, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-ic.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 423, 100, 30));

        eror.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        eror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(eror, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 446, 242, 28));
        jPanel5.add(overtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("In Over Time");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));
        jPanel5.add(IOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Late Grace Time:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 292, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Early Grace Time:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 322, -1, -1));
        jPanel5.add(LE, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 292, -1, -1));
        jPanel5.add(EE, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 322, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("If Late Exceed After ");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("If Early Exceed Before");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 322, -1, -1));
        jPanel5.add(EA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));
        jPanel5.add(EB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        nights.setBackground(new java.awt.Color(255, 255, 255));
        nights.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nights.setText("Night Shift");
        nights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightsActionPerformed(evt);
            }
        });
        jPanel5.add(nights, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 82, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel-btn-icon-20.png"))); // NOI18N
        jButton16.setText("Close");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 519, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 126, 1));
        jLabel1.setText("Arrange Shifts");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Break Time In ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Break Time Out");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));
        jPanel5.add(lunchin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));
        jPanel5.add(lunchout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(mon.isSelected())

        {int mond=2;
            String a1=shift1.getSelectedItem().toString();
            String a3=schedule1.getSelectedItem().toString();
            try
            {

                String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+mond+"' and Num_Run_Name='"+a1+"' and Sch_NAME='"+a3+"'";             // Create query string to insert name into table

                Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                pst.executeUpdate();
               eror.setText("Command Successfull");
art.reset();
                //                                    Execute Query
                //pst.setString(1,str1);
                //          pst.setString(2,p);
                // Close the open connection
            }
            catch(Exception e)
            {eror.setText("Command Unsuccessfull");

            }}
            if(tues.isSelected())
            {int tuesd=3;

                String a1=shift1.getSelectedItem().toString();
                String a3=schedule1.getSelectedItem().toString();
                try
                {

                    String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+tuesd+"' and Num_Run_Name='"+a1+"' and Sch_NAME='"+a3+"'";
                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();
art.reset();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(wed.isSelected())
            {int wednesd=4;

                String a1=shift1.getSelectedItem().toString();
                String a3=schedule1.getSelectedItem().toString();
                try
                {

                    String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+wednesd+"' and Num_Run_Name='"+a1+"' and Sch_NAME='"+a3+"'";
                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();
                    eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }

            }
            if(thurs.isSelected())
            {int thursd=5;
                String a1=shift1.getSelectedItem().toString();
                String a3=schedule1.getSelectedItem().toString();
                try
                {

                    String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+thursd+"' and Num_Run_Name='"+a1+"' and Sch_NAME='"+a3+"'";
                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(fri.isSelected())
            {int frid=6;
                String a1=shift1.getSelectedItem().toString();
                String a3=schedule1.getSelectedItem().toString();
                try
                {

                    String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+frid+"' and Num_Run_Name='"+a1+"' and Sch_NAME='"+a3+"'";
                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(sat.isSelected())
            {int saturd=7;
                String a1=shift1.getSelectedItem().toString();
                String a3=schedule1.getSelectedItem().toString();
                try
                {

                    String query = "DELETE FROM `num_run_days` WHERE `s_Days`='"+saturd+"' and Num_Run_Name='"+a3+"' and Sch_name='"+a1+"'";
                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();
                    eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }}
                if(sun.isSelected())
                {int sund=1;
                    String a1=shift1.getSelectedItem().toString();
                    String a3=schedule1.getSelectedItem().toString();
                    try
                    {

                        String query ="DELETE FROM `num_run_days` WHERE `s_Days`='"+sund+"' and Num_Run_Name='"+a3+"' and Sch_name='"+a1+"'";
                        Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                        Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                        PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                        pst.executeUpdate();eror.setText("Command Successfull");
                        //                                    Execute Query
                        //pst.setString(1,str1);
                        //          pst.setString(2,p);
                        // Close the open connection
                        art.reset();
                    }
                    catch(Exception e)
                    {
                    eror.setText("Command Unsuccessfull");}
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(nights.isSelected())
        {            d1="2017-01-01"; d2="2017-01-02";} else {            d1="2017-01-01"; d2="2017-01-01";}
        String b1=shift1.getSelectedItem().toString();

            String b2=shiftid.getSelectedItem().toString();

            String b3=schedule1.getSelectedItem().toString();

            String b4=scheduleid.getSelectedItem().toString();

            int b5=sstarttime.getHours();
            int b6=sstarttime.getMinutes();
            int b7=sstarttime.getSeconds();

            int b8=sendtime.getHours();
            int b9=sendtime.getMinutes();
            int b10=sendtime.getSeconds();

            int b11=overtime.getHours();
            int b12=overtime.getMinutes();
            int b13=overtime.getSeconds();
            
            int b14=IOT.getHours();
            int b15=IOT.getMinutes();
            int b16=IOT.getSeconds();
            
            int b17=LE.getHours();
            int b18=LE.getMinutes();
            int b19=LE.getSeconds();
            
            int b20=EE.getHours();
            int b21=EE.getMinutes();
            int b22=EE.getSeconds();
            
            int b23=EA.getHours();
            int b24=EA.getMinutes();
            int b25=EA.getSeconds();
            
            int b26=EB.getHours();
            int b27=EB.getMinutes();
            int b28=EB.getSeconds();
        if(b1.isEmpty() || b2.isEmpty() || b3.isEmpty() || b4.isEmpty() || b5 == 00 && b6 == 00 && b7 == 00 || b8 == 00 && b9 == 00 && b10 == 00 || b11 == 00 && b12 == 00 && b13 == 00 || b14 == 00 && b15 == 00 && b16 == 00 || b17 == 00 && b18 == 00 && b19 == 00 || b20 == 00 && b21 == 00 && b22 == 00 || b23 == 00 && b24 == 00 && b25 == 00 || b26 == 00 && b27 == 00 && b28 == 00)
{eror.setText("Please Insert Complete Details");}else{
        if(mon.isSelected())

        {int mond=2;
            String a1=shift1.getSelectedItem().toString();

            String a2=shiftid.getSelectedItem().toString();

            String a3=schedule1.getSelectedItem().toString();

            String a4=scheduleid.getSelectedItem().toString();

            int a5=sstarttime.getHours();
            int a6=sstarttime.getMinutes();
            int a7=sstarttime.getSeconds();

            int a8=sendtime.getHours();
            int a9=sendtime.getMinutes();
            int a10=sendtime.getSeconds();

            int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();

            try
            {

                String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+mond+"','"+mond+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                pst.executeUpdate();eror.setText("Command Successfull");
art.reset();
                //                                    Execute Query
                //pst.setString(1,str1);
                //          pst.setString(2,p);
                // Close the open connection
            }
            catch(Exception e)
            {eror.setText("Command Unsuccessfull");

            }}
            if(tues.isSelected())
            {int tuesd=3;
                String a1=shift1.getSelectedItem().toString();

                String a2=shiftid.getSelectedItem().toString();

                String a3=schedule1.getSelectedItem().toString();

                String a4=scheduleid.getSelectedItem().toString();

                int a5=sstarttime.getHours();
                int a6=sstarttime.getMinutes();
                int a7=sstarttime.getSeconds();

                int a8=sendtime.getHours();
                int a9=sendtime.getMinutes();
                int a10=sendtime.getSeconds();

            int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                try
                {

                    String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+tuesd+"','"+tuesd+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();
eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(wed.isSelected())
            {int wednesd=4;
                String a1=shift1.getSelectedItem().toString();

                String a2=shiftid.getSelectedItem().toString();

                String a3=schedule1.getSelectedItem().toString();

                String a4=scheduleid.getSelectedItem().toString();

                int a5=sstarttime.getHours();
                int a6=sstarttime.getMinutes();
                int a7=sstarttime.getSeconds();

                int a8=sendtime.getHours();
                int a9=sendtime.getMinutes();
                int a10=sendtime.getSeconds();

                int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                try
                {

                    String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+wednesd+"','"+wednesd+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }

            }
            if(thurs.isSelected())
            {int thursd=5;
                String a1=shift1.getSelectedItem().toString();

                String a2=shiftid.getSelectedItem().toString();

                String a3=schedule1.getSelectedItem().toString();

                String a4=scheduleid.getSelectedItem().toString();

                int a5=sstarttime.getHours();
                int a6=sstarttime.getMinutes();
                int a7=sstarttime.getSeconds();

                int a8=sendtime.getHours();
                int a9=sendtime.getMinutes();
                int a10=sendtime.getSeconds();

                int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                try
                {

                 String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+thursd+"','"+thursd+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";

                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(fri.isSelected())
            {int frid=6;
                String a1=shift1.getSelectedItem().toString();

                String a2=shiftid.getSelectedItem().toString();

                String a3=schedule1.getSelectedItem().toString();

                String a4=scheduleid.getSelectedItem().toString();

                int a5=sstarttime.getHours();
                int a6=sstarttime.getMinutes();
                int a7=sstarttime.getSeconds();

                int a8=sendtime.getHours();
                int a9=sendtime.getMinutes();
                int a10=sendtime.getSeconds();

                int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                try
                {

                    String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+frid+"','"+frid+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }
            }
            if(sat.isSelected())
            {int saturd=7;
                String a1=shift1.getSelectedItem().toString();

                String a2=shiftid.getSelectedItem().toString();

                String a3=schedule1.getSelectedItem().toString();

                String a4=scheduleid.getSelectedItem().toString();

                int a5=sstarttime.getHours();
                int a6=sstarttime.getMinutes();
                int a7=sstarttime.getSeconds();

                int a8=sendtime.getHours();
                int a9=sendtime.getMinutes();
                int a10=sendtime.getSeconds();

                int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                try
                {

                    String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+saturd+"','"+saturd+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                    Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                    Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                    PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                    pst.executeUpdate();eror.setText("Command Successfull");
                    //                                    Execute Query
                    //pst.setString(1,str1);
                    //          pst.setString(2,p);
                    // Close the open connection
                }
                catch(Exception e)
                {eror.setText("Command Unsuccessfull");
                }}
                if(sun.isSelected())
                {int sund=1;
                    String a1=shift1.getSelectedItem().toString();

                    String a2=shiftid.getSelectedItem().toString();

                    String a3=schedule1.getSelectedItem().toString();

                    String a4=scheduleid.getSelectedItem().toString();

                    int a5=sstarttime.getHours();
                    int a6=sstarttime.getMinutes();
                    int a7=sstarttime.getSeconds();

                    int a8=sendtime.getHours();
                    int a9=sendtime.getMinutes();
                    int a10=sendtime.getSeconds();

                    int a11=overtime.getHours();
            int a12=overtime.getMinutes();
            int a13=overtime.getSeconds();
            
            int a14=IOT.getHours();
            int a15=IOT.getMinutes();
            int a16=IOT.getSeconds();
            
            int a17=LE.getHours();
            int a18=LE.getMinutes();
            int a19=LE.getSeconds();
            
            int a20=EE.getHours();
            int a21=EE.getMinutes();
            int a22=EE.getSeconds();
            
            int a23=EA.getHours();
            int a24=EA.getMinutes();
            int a25=EA.getSeconds();
            
            int a26=EB.getHours();
            int a27=EB.getMinutes();
            int a28=EB.getSeconds();
                    try
                    {

                        String query = "INSERT INTO `num_run_days` VALUES('"+a4+"','"+a3+"','"+d1+" "+a5+":"+a6+":"+a7+"','"+d2+" "+a8+":"+a9+":"+a10+"','"+sund+"','"+sund+"','"+a2+"','"+a1+"','"+d2+" "+a11+":"+a12+":"+a13+"','"+d1+" "+a14+":"+a15+":"+a16+"','"+d1+" "+a17+":"+a18+":"+a19+"','"+d2+" "+a20+":"+a21+":"+a22+"','"+d1+" "+a23+":"+a24+":"+a25+"','"+d2+" "+a26+":"+a27+":"+a28+"')";             // Create query string to insert name into table

                        Class.forName("com.mysql.jdbc.Driver");                             // Load Driver class

                        Connection con = DriverManager.getConnection(url,id,pass);  // Connect to Database using credentials

                        PreparedStatement pst= con.prepareStatement(query);                             // Create statement
                        pst.executeUpdate();
                     reset();eror.setText("Command Successfull");
art.reset();                        //                                    Execute Query
                        //pst.setString(1,str1);
                        //          pst.setString(2,p);
                        // Close the open connection
                    }
                    catch(Exception e)
                    {eror.setText("Command Unsuccessfull");
                    }}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void schedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule1ActionPerformed
        String s13=schedule1.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,id,pass);
            PreparedStatement pst=conn.prepareStatement("SELECT Num_RunID,name FROM `num_run` where name='"+s13+"'");

            ResultSet rst1=pst.executeQuery();

            while(rst1.next()){
                scheduleid.addItem(rst1.getString("Num_RunID"));
                scheduleid.setSelectedItem(rst1.getString("Num_RunID"));

            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error combo"+ex);
        }
    }//GEN-LAST:event_schedule1ActionPerformed

    private void tuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed

    }//GEN-LAST:event_monActionPerformed

    private void shift1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shift1ActionPerformed
        String s12=shift1.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,id,pass);
            PreparedStatement pst=conn.prepareStatement("SELECT name,sch_ID,timein,timeout FROM `shift` where name='"+s12+"'");

            ResultSet rst1=pst.executeQuery();

            while(rst1.next()){
                shiftid.addItem(rst1.getString("sch_ID"));
                shiftid.setSelectedItem(rst1.getString("sch_ID"));
                sstarttime.setTime(rst1.getTime("timein"));
                sendtime.setTime(rst1.getTime("timeout"));
                IOT.setTime(rst1.getTime("timein"));
                overtime.setTime(rst1.getTime("timeout"));
                LE.setTime(rst1.getTime("timein"));
                EE.setTime(rst1.getTime("timeout"));
                EA.setTime(rst1.getTime("timein"));
                EB.setTime(rst1.getTime("timeout"));
            }

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error combo"+ex);
        }
    }//GEN-LAST:event_shift1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                     this.setVisible(false);        // TODO add your handling code here:
art.reset();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void nightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shiftdaystable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shiftdaystable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shiftdaystable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shiftdaystable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shiftdaystable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lu.tudor.santec.jtimechooser.JTimeChooser EA;
    private lu.tudor.santec.jtimechooser.JTimeChooser EB;
    private lu.tudor.santec.jtimechooser.JTimeChooser EE;
    private lu.tudor.santec.jtimechooser.JTimeChooser IOT;
    private lu.tudor.santec.jtimechooser.JTimeChooser LE;
    private javax.swing.JLabel eror;
    private javax.swing.JCheckBox fri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private lu.tudor.santec.jtimechooser.JTimeChooser lunchin;
    private lu.tudor.santec.jtimechooser.JTimeChooser lunchout;
    private javax.swing.JCheckBox mon;
    private javax.swing.JCheckBox nights;
    private lu.tudor.santec.jtimechooser.JTimeChooser overtime;
    private javax.swing.JCheckBox sat;
    private javax.swing.JComboBox<String> schedule1;
    private javax.swing.JComboBox<String> scheduleid;
    private lu.tudor.santec.jtimechooser.JTimeChooser sendtime;
    private javax.swing.JComboBox<String> shift1;
    private javax.swing.JComboBox<String> shiftid;
    private lu.tudor.santec.jtimechooser.JTimeChooser sstarttime;
    private javax.swing.JCheckBox sun;
    private javax.swing.JCheckBox thurs;
    private javax.swing.JCheckBox tues;
    private javax.swing.JCheckBox wed;
    // End of variables declaration//GEN-END:variables
}
